### ISSUE TITLE
Cinder version?

### ISSUE THREAD

**Issue by Dazzid** [trippedout/CinderMyo#1]
Hello
I'm searching for the myo block for cinder, I couldn't compile your block for cinder 0.9.1, for which cinder version it was made?
Thanks

**Comment by trippedout** [comment]
oh wow - just dug thru the xcode project and [found this](https://github.com/trippedout/CinderMyo/blob/master/xcode/MyoCinder.xcodeproj/project.pbxproj#L313) so it looks like it was 0.8.6 

def havent updated or tested against the latest version of cinder and im _sure_ the myo folks have updated their api's too, tho backwards compat might still be a thing
